apiVersion: v1
kind: Service
metadata:
  name: backend-orchestrator
  namespace: general-chatbot-app
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: backend-orchestrator
