apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-orchestrator-config
  namespace: general-chatbot-app
data:
  DATABASE_URL: "postgresql://postgres:BTxg8LN5lH@postgres.data.svc.cluster.local:5432/chatbot_db"
  REDIS_URL: "redis://redis.data.svc.cluster.local:6379/0"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.data.svc.cluster.local:9092"
  DEFAULT_LLM_PROVIDER: "gemini"
  FALLBACK_LLM_PROVIDER: "anthropic"
  SERVICE_NAME: "backend-orchestrator"
  SERVICE_VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
  SESSION_TIMEOUT_MINUTES: "30"
  MAX_CONVERSATION_HISTORY: "50"
  RATE_LIMIT_PER_MINUTE: "60"
  RATE_LIMIT_PER_HOUR: "1000"
  DEBUG: "false"
  RELOAD: "false"
