apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-orchestrator
  namespace: general-chatbot-app
  labels:
    app: backend-orchestrator
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-orchestrator
  template:
    metadata:
      labels:
        app: backend-orchestrator
        version: v1
    spec:
      containers:
      - name: backend-orchestrator
        image: localhost:5000/backend-orchestrator:v1.0.0
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: backend-orchestrator-config
        - secretRef:
            name: backend-orchestrator-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
