apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-local
  labels:
    type: local
spec:
  # 'Delete' policy ensures the PV is removed from Kubernetes when the PVC is deleted.
  # For hostPath, this does NOT delete the data on the host machine's directory.
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # IMPORTANT: You must create this directory on your host machine first.
    # For example, on Windows/Mac with Docker Desktop, you can run: mkdir -p /c/Users/User/kube-data/postgres
    path: "/run/desktop/mnt/host/c/Users/User/kube-data/postgres" # Points to C:\Users\User\kube-data\postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  labels:
    app: postgres
  namespace: data #default
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: standard
  resources:
    requests:
      storage: 5Gi
