apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: general-chatbot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        ports:
        - containerPort: 8004
        env:
        - name: DATABASE_URL
          value: postgresql://chatbot_user:chatbot_password@postgres:5432/chatbot_db
        volumeMounts:
        - name: app-volume
          mountPath: /app
      volumes:
      - name: app-volume
        hostPath:
          path: /app/auth_identity_service
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  ports:
  - port: 8004
    targetPort: 8004
  selector:
    app: auth-service
