apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: data #general-chatbot-app
spec:
  type: ClusterIP
  ports:
  - port: 2181
    targetPort: 2181
  selector:
    app: zookeeper
