apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowledge-base-service
  namespace: general-chatbot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knowledge-base-service
  template:
    metadata:
      labels:
        app: knowledge-base-service
    spec:
      containers:
      - name: knowledge-base-service
        image: knowledge-base-service:latest
        ports:
        - containerPort: 8001
        # Best practice: Construct the database URL from secrets and known service names
        # This avoids hardcoding credentials and improves configurability.
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "postgresql+psycopg2://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@my-rag-postgres-postgresql.data.svc.cluster.local:5432/rag_db"
        volumeMounts:
        - name: app-volume
          mountPath: /app
      volumes:
      - name: app-volume
        hostPath:
          # Note: hostPath is suitable for single-node local development but is not recommended
          # for production as it ties the pod to a specific node.
          path: /app/integrations/knowledge_base_service
---
apiVersion: v1
kind: Service
metadata:
  name: knowledge-base-service
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: knowledge-base-service
